baseurl = "https://saadtarik.netlify.com/"
title = "Saad Tarik"
googleAnalytics = "UA-139537268-1"
disqusShortname = "saad-tarik.disqus.com"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
copyright = "Saad Tarik"
canonifyurls = true
theme = "hugo-kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "Saad Tarik"
    github = "https://github.com/saadtarik"
    gitlab = ""
    linkedin = "https://www.linkedin.com/in/saad-tarik-96240636/"
    facebook = ""
    twitter = "https://twitter.com/saadtarik"
    instagram = "https://www.instagram.com/saadtarik/"

[params]
    tagline = "Saad Tarik's Website"


