baseurl = "https://saadtarik.netlify.com//"
languageCode = "en-us"
title = "Saad Tarik"
theme = "hugo-theme-jane"
googleAnalytics = "UA-139537268-1"
disqusShortname = "saad-tarik.disqus.com"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
copyright = "Saad Tarik"
color_theme = "ocean"
font = "playfair"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/saadtarik"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/saadtarik"
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/saad-tarik-96240636/"
[[menu.main]]
    name = "Projects"
    url = "/projects/"
[[menu.main]]
    name = "Contact"
    url = "/contact/"

[params]
    description = "Saad Tarik's Website"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

[params.social]
    b-github = "https://github.com/saadtarik"
    c-linkedin = "https://www.linkedin.com/in/saad-tarik-96240636/"
    d-twitter = "https://twitter.com/saadtarik"
    e-instagram = "https://www.instagram.com/saadtarik/"

