baseurl = "https://saadtarik.netlify.com/"
title = "Saad Tarik"
googleAnalytics = "UA-139537268-1"
disqusShortname = "saad-tarik"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
copyright = "Saad Tarik"
canonifyurls = true
theme = "hugo-kiera"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "Saad Tarik"
    github = "saadtarik"
    gitlab = ""
    linkedin = "saadtarik"
    facebook = ""
    twitter = "saadtarik"
    instagram = "saadtarik"

[params]
    tagline = ""


